# GPG signing of commits - necessary for GPG to open passphrase prompt during
# signing
export GPG_TTY="$(tty)"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

#eval "$(rbenv init -)"

# For aws-sdk to work with configured profiles. Override AWS_PROFILE for
# per-env/role profiles (lifeomic-prod-admin, lifeomic-prod-support, etc)
# Note: privileged roles like Support require re-login w/ CLI using different
# lifeomic-master source role
export AWS_SDK_LOAD_CONFIG=1
#export AWS_PROFILE=lifeomic-dev
#export AWS_DEFAULT_PROFILE=lifeomic-dev
#export LIFEOMIC_TARGET_ENVIRONMENT=lifeomic-dev
#export AWS_REGION=us-east-1
#export LIFEOMIC_LOGIN_USERNAME=james.beavers

# Mobile Stuff

#export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
#export BITRISEIO_ANDROID_KEYSTORE_ALIAS='e2eFakeKeystore'
#export BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD='Password'
#export BITRISEIO_ANDROID_KEYSTORE_PASSWORD='Password'

export ANDROID_HOME=$HOME/android
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH="$HOME/.local/bin:$PATH"

export PS1="%n@%M--%2C%# "
