#!/usr/bin/env bash

# particularly useful for rebases where --no-verify does not work skip hooks
if [ "$NO_VERIFY" ]; then
    echo 'NO_VERIFY detected. Skipping jira ticket commit message insert.'
    exit 0
fi

COMMIT_MSG_FILE="$1"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

check-message () {
    git-conventional-commits commit-msg-hook --config "$SCRIPT_DIR/git-conventional-commits.json" "$COMMIT_MSG_FILE"
}

check-message
source "$SCRIPT_DIR/helpers.sh"
execute_local_hook
