#!/usr/bin/env node

const env = process.argv[2] || 'dev';
console.error(`Using env '${env}'`);

const Configstore = require('configstore');
const conf = new Configstore('lifeomic-cli');
const config = conf.get(env);
process.stdout.write(config.tokens.accessToken);
