export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# GPG signing of commits - necessary for GPG to open passphrase prompt during
# signing
export GPG_TTY="$(tty)"

# disable using zwc 'compiled' zshrc to avoid unexpected divergence...
# oh-my-zsh will enable this by default annoyingly
export ZSH_DISABLE_COMPFIX=true

#export AWS_DEFAULT_REGION='us-east-1'
export AWS_DEFAULT_PROFILE='fusion-dev-admin'
export AWS_PROFILE='fusion-dev-admin'

# https://github.com/kennyp/asdf-golang#version-selection
#export ASDF_GOLANG_MOD_VERSION_ENABLED=true

# TODO: linux support
export PATH=${PATH}:/opt/homebrew/bin
#. "$(brew --prefix asdf)/libexec/asdf.sh"
export PATH="$(go env GOPATH)/bin:$PATH"

export PATH="$HOME/.local/bin:$PATH"
# breaks asdf?
export PATH="$PATH:$(yarn global bin)"

#echo zshenv: $PATH


export ANDROID_HOME=${HOME}/android-sdk
#export PATH=${PATH}:${ANDROID_HOME}/emulator
#export PATH=${PATH}:${ANDROID_HOME}/tools
#export PATH=${PATH}:${ANDROID_HOME}/tools/bin
#export PATH=${PATH}:${ANDROID_HOME}/platform-tools

# needed for rootless
# https://docs.docker.com/engine/security/rootless/
#export DOCKER_HOST=unix:///run/user/1000/docker.sock
#export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"

# Handled by OMZsh now (HISTFILE=/.zsh_history)
# export HISTSIZE=100000 (50k OMZsh default)
# export SAVEHIST=100000 (10k OMZsh default

#TODO: why did I add this?
# export PS1="%n@%M--%2C%# "
# TODO: delete this cruft
#visually breaks prompt sometimes right now export PS1="\[\e[48;5;237m \W \$\e[0m \]" export PS1='$USER@$(hostname):$(basename $PWD)$ '
#export PS1="\[\033[0;35m\]\h\[\033[0;33m\] \w\[\033[00m\]: ???"
# hide computer name

export EDITOR=/opt/homebrew/bin/nvim

# TODO: Disable installing husky hooks. Global hook will execute local hooks
# programmatically. Re-enabled for now.. need to figure out a better hybrid
# approach
export HUSKY=1

export AWS_PAGER=""
export AWS_REGION="us-gov-west-1"
